name: Check
on:
  push:
    branches:
      - master
jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run linter
        run: npm run lint
